ProyectoVotaciones/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoVotaciones.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PresidentsCandidate()
        {
            ViewBag.Message = "Your Candidate President page.";

            return View();
        }

        public ActionResult CandidateVicepresidents()
        {
            ViewBag.Message = "Your Candidate VicePresident´s page.";

            return View();
        }
    }
}

ProyectoVotaciones/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace ProyectoVotaciones.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

ProyectoVotaciones/Views/Home/CandidateVicepresidents.cshtml
@{
    ViewBag.Title = "CandidateVicepresidents";
    Layout = null;
}
@Styles.Render("~/Content/PageStylecss")

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <div class="container" id="tourpackages-carousel">
      <div class="row">

        <div class="col-lg-12">
          <h1>CANDIDATOS A VICEPRESIDENCIA
            <a class="btn icon-btn btn-primary pull-right" href="@Url.Action("PresidentsCandidate", "Home")">
            <span class="glyphicon btn-glyphicon img-circle" ></span> VOTO EN BLANCO</a>
              </h1></div>

        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <div class="thumbnail">
              <div class="caption">
                  <div class='col-lg-12'>
                      <div align="center">
                      <img src="https://firebasestorage.googleapis.com/v0/b/candidateimg.appspot.com/o/21F%2FCandidatoEdwin.jpg?alt=media&token=ed51881b-f08a-43b1-befa-68aa6651b52e"
                           class="img-circle" width="100">
                      </div>
                  </div>

                <div class='col-lg-12 well well-add-card'>
                    <h4>Oscar Ortiz</h4>
                </div>

                <div class='col-lg-12'>
                    <p>21F</p>
                </div>
                <a type="button" class="btn btn-primary btn-xs btn-update btn-add-card" href="@Url.Action("PresidentsCandidate", "Home")">VOTAR</a>
            </div>
          </div>
        </div>

      </div>
    </div>

ProyectoVotaciones/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = null;
}
@Styles.Render("~/Content/Homecss")

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/indexjs")

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<body class="center-block">
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">


                            <div align="center"><img src="~/Content/Pictures/Logo/Oep.png" class="img-circle" width="100"></div>

                            <h3 class="text-center text-info">ELECIONES PRESIDENCIALES</h3>
                            <h4 class="text-center text-info">BOLIVIA</h4>
                            <h5 class="text-center text-info">2020 - 2025</h5>

                            <div class="form-group">
                                <label for="password" class="text-info">Cedula de Identidad:</label><br>
                                <input type="text" name="password" id="password" class="form-control">
                            </div>

                            <div class="form-group">
                                <a class="btn btn-info btn-md" href="@Url.Action("CandidateVicepresidents", "Home")">INGRESAR</a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

ProyectoVotaciones/Views/Home/PresidentsCandidate.cshtml
@{
    ViewBag.Title = "PresidentsCandidate";
    Layout = null;

}
@Styles.Render("~/Content/PageStylecss")

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container" id="tourpackages-carousel">
    <div class="row">

        <div class="col-lg-12">
            <h1>
                CANDIDATOS A PRESIDENTE
                <a class="btn icon-btn btn-primary pull-right" href="@Url.Action("Index", "Home")">
                    <span class="glyphicon btn-glyphicon img-circle"></span> VOTO EN BLANCO
                </a>
            </h1>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <div class="thumbnail">
                <div class="caption">
                    <div class='col-lg-12'>
                        <div align="center"><img src="https://firebasestorage.googleapis.com/v0/b/proyectoionic-caad0.appspot.com/o/oscar.jpg?alt=media&token=f97d2383-f5af-45e5-bc99-9e499e1f7744" class="img-circle" width="100"></div>
                    </div>

                    <div class='col-lg-12 well well-add-card'>
                        <h4>Oscar Ortiz</h4>
                    </div>

                    <div class='col-lg-12'>
                        <p>21F</p>
                    </div>
                    <a type="button" class="btn btn-primary btn-xs btn-update btn-add-card" href="@Url.Action("Index", "Home")">VOTAR</a>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoVotaciones/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

ProyectoVotaciones/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoVotaciones/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}